### ISSUE TITLE
Branch gige_example not merged

### ISSUE THREAD

**Issue by xluciano** [xmos/lib_ethernet#42]
The branch gige_example is not merged.

Some of the commits (601e44d, 31ea189 and 9e7cd5c) include changes to the main functionality.

The changes trace back to 2015 and it is not clear if they are still needed.

**Comment by ed-xmos** [comment]
I have been through this and lib items (in above hashes) have been addressed and example completely revamped. I am satisfied there is nothing of value here so closing the issue and deleting the branch.
