### ISSUE TITLE
100Mbit MAC client state always ignores link updates

### ISSUE THREAD

**Issue by larry-xmos** [xmos/lib_ethernet#5]
See mii_ethernet_mac.xc

Status update state is initialised to "ignoring" and will stay like that. Code that generates ETH_IF_STATUS notification to user is unreachable.

**Comment by larry-xmos** [comment]
As a result xTCP will never signal link up to uIP (see xtcp.xc)

**Comment by mbanth** [comment]
Appears to have been resolved by Pull Request #11.
