### ISSUE TITLE
lib_ethernet with RGMII interface causes random sending delays

### ISSUE THREAD

**Issue by aritec** [xmos/lib_ethernet#51]
Using lib_ethernet with RGMII interface causes random sending delays up to 21s.
The reason for this is on the rgmii_10_100_master_tx_pins task:

```
int word_count = byte_count >> 2;
tail_byte_count = byte_count & 3;  

// Ensure that the interframe gap is respected
tmr when timerafter(ifg_time) :> ifg_time;

// Send the preamble
{tmp1, tmp2} = zip2(0x55555555, 0x55555555);`

```
ifg_time is calculated at the end of the last sent buffer.
If there is a idle time between buffers for more than 21 seconds, the timerafter(ifg_time) adds another (up to 21 seconds) delay before handling the buffer!
tmr is a 2^32 bit 100MHz counter but timerafter() can only handle delays up to 2^31 ticks. Longer delays are handelt after a "rollover" of 42 seconds.

See: https://www.xcore.com/viewtopic.php?t=8771

**Comment by ed-xmos** [comment]
Thanks for logging this and providing a helpful amount of detail. I can see how the timer wrap issue would cause this issue. I'm currently updating the library over the next few weeks and will look into this.

**Comment by ed-xmos** [comment]
This should be fixed now (in develop at least). https://github.com/xmos/lib_ethernet/pull/71
If you experience any further issues, please feel free to re-open.
