### ISSUE TITLE
tests/test_rx_queues fails on profiles a and b for RGMII 1000Mbit

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_ethernet#57]
In https://github.com/xmos/lib_ethernet/pull/54

Profile c does work however:

```
ERROR: Line 0 of output not found in expected
  Actual  : Packet 21 instead of 20
ERROR: Line 1 of output not found in expected
  Actual  : Packet 22 instead of 21
ERROR: Line 2 of output not found in expected
  Actual  : Packet 23 instead of 22
ERROR: Length of expected output less than output
Fail

[gw3] FAILED test_rx_queues.py::test_rx_queues[rgmii-125MHz-hp-xs2-a] 
[gw5] PASSED test_rx_queues.py::test_rx_queues[rgmii-125MHz-hp-xs2-c] 
[gw0] PASSED test_rx_queues.py::test_rx_queues[mii-25MHz-rt_hp-xs2-a] ERROR: Line 0 of output not found in expected
  Actual  : Packet 73 instead of 72
ERROR: Line 1 of output not found in expected
  Actual  : Packet 74 instead of 73
ERROR: Line 2 of output not found in expected
  Actual  : Packet 76 instead of 74
ERROR: Length of expected output less than output
Fail

[gw4] FAILED test_rx_queues.py::test_rx_queues[rgmii-125MHz-hp-xs2-b] 
[gw2] PASSED test_rx_queues.py::test_rx_queues[rgmii-25MHz-hp-xs2-a] 
[gw1] PASSED test_rx_queues.py::test_rx_queues[mii-25MHz-rt_hp-xs2-b] 
```

It looks like packets are being dropped. Increasing the inter-frame-gap significantly results in a pass.

**Comment by ed-xmos** [comment]
Edit - looks like it used to pass:

http://srv-bri-jcim0:8080/blue/rest/organizations/jenkins/pipelines/XMOS/pipelines/lib_ethernet/branches/PR-58/runs/1/nodes/888/log/?start=272

Wondering if this is a tools version issue?

**Comment by shuchitak** [comment]
I have fixed the failures for type a and b tests. There was an error in _max_mbps calculation in DataLimiter, which was affecting the interframe gap in packets sent by the simulator. Fix is committed [here](https://github.com/xmos/lib_ethernet/commit/1e8fd8a4fd4a4ec79ce60e2502da7ec2800ae287#diff-c562416013c6d05ae950c5a8c6723b754af0a2365a14e32b20194ee7245ff3efR47). I have also increased END_OF_TEST_TIME to fix some timeout errors I was seeing with type c tests

**Comment by shuchitak** [comment]
After the above fix, I still notice that type c tests fail intermittently, roughly about a couple of times every 10 runs. The seed used in random.seed() is generated randomly, so the test fails or passes depending on the seed. When the test fails, the DUT reports high priority packets being dropped. 

I can recreate the failure with xmostest as well, running the master branch with xmostest.

If I increase the core clock freq from 500MHz to 600MHz, I can confirm that the test passes reliably.

I've listed below 2 seed values, for which the test fails with pyxsim/xmostest, in case we want to recreate the failure.

seed = 1949281052092687998 # fails with pyxsim
seed = 1164115433906158532 # fails on xmostest

**Comment by shuchitak** [comment]
I'll added a separate issue about the failing type 'c' test
